### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by nottrobin** [powersj/ubuntu-release-info#1]
When I tried to pip install this it failed:

``` bash
$ pip3 install ubuntu-release-info
Collecting ubuntu-release-info
  Downloading ubuntu-release-info-19.1.tar.gz (5.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/robin/Projects/ubuntu.com/env3/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8kkb2zxp/ubuntu-release-info/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8kkb2zxp/ubuntu-release-info/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-8kkb2zxp/ubuntu-release-info/pip-egg-info
         cwd: /tmp/pip-install-8kkb2zxp/ubuntu-release-info/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8kkb2zxp/ubuntu-release-info/setup.py", line 9, in <module>
        with open(REQUIREMENTS_FILE, 'r') as req_file:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-8kkb2zxp/ubuntu-release-info/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by powersj** [comment]
Thanks for the bug! Fixed in https://github.com/powersj/ubuntu-release-info/commit/dfc0a54b07cbe1aad2900e8cefa3374577f6debf and release 20.1 uploaded to pypi
